/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion2_laboratorio5;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author KATHERINE
 */
public class Power_Squad extends javax.swing.JFrame {

    /**
     * Creates new form Power_Squad
     */
    public Power_Squad() {
        initComponents();
        tf_tipo_es_he.setEnabled(false);
        tf_tipo_es_vi.setEnabled(false);
        villanos_menu.setEnabled(false);
       heroes_menu.setEnabled(false);
       
       
       
//       DefaultComboBoxModel model=(DefaultComboBoxModel)cb_escuadron_vi.getModel();
//               model.addElement(escuadron_villanos);
//               cb_heroes.setModel(model);
//               
//     DefaultComboBoxModel model2=(DefaultComboBoxModel)cb_escuadron_he.getModel();
//       model.addElement(Escuadron_heroe);
//               cb_villanos.setModel(model2);
//               
//      DefaultComboBoxModel model3=(DefaultComboBoxModel)cb_villanos.getModel();
//                model.addElement(villanos);
//               cb_villanos.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        super_heroes = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_nombre_he = new javax.swing.JTextField();
        tf_debilidad_he = new javax.swing.JTextField();
        tf_poder_he = new javax.swing.JTextField();
        sp_fuerza_he = new javax.swing.JSpinner();
        sp_fisica_he = new javax.swing.JSpinner();
        sp_mental_he = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_heroes = new javax.swing.JList<>();
        bt_agregar_he = new javax.swing.JButton();
        bt_modificar_he = new javax.swing.JButton();
        bt_eliminar_he = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_xheroes = new javax.swing.JList<>();
        Villanos = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_nombre_vi = new javax.swing.JTextField();
        tf_debilidad_vi = new javax.swing.JTextField();
        tf_poder_vi = new javax.swing.JTextField();
        sp_fuerza_vi = new javax.swing.JSpinner();
        sp_fisica_vi = new javax.swing.JSpinner();
        sp_mental_vi = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_villanos = new javax.swing.JList<>();
        bt_agregar_vi = new javax.swing.JButton();
        bt_modificar_vi = new javax.swing.JButton();
        bt_eliminar_vi = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_xvillanos = new javax.swing.JList<>();
        Escuadron_villano = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre_es_vi = new javax.swing.JTextField();
        tf_lema_es_vi = new javax.swing.JTextField();
        tf_localidad_es_vi = new javax.swing.JTextField();
        tf_tipo_es_vi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_escuadron_villanos = new javax.swing.JList<>();
        bt_agregar_es_vi = new javax.swing.JButton();
        bt_mod_es_vi = new javax.swing.JButton();
        bt_elim_es_vi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cb_villanos = new javax.swing.JComboBox<>();
        Escuadron_heroe = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_escuadron_heroes = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        tf_localidad_es_he = new javax.swing.JTextField();
        tf_nombre_es_he = new javax.swing.JTextField();
        tf_lema_es_he = new javax.swing.JTextField();
        bt_elim_es_he = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bt_mod_es_he = new javax.swing.JButton();
        bt_agregar_es_he = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_tipo_es_he = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_heroes = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        generar_arbol = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jmi_escuadron_villano = new javax.swing.JMenuItem();
        jmi_escuadronheroe = new javax.swing.JMenuItem();
        heroes_menu = new javax.swing.JMenuItem();
        villanos_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel13.setText("Super Heores");

        jLabel14.setText("Nombre");

        jLabel15.setText("Debilidad");

        jLabel16.setText("fuerza");

        jLabel17.setText("Poder");

        jLabel18.setText("Escuadron");

        jLabel19.setText("Agilidad Fisica");

        jLabel20.setText("Agilidad mental");

        jl_heroes.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(jl_heroes);

        bt_agregar_he.setText("Agregar");

        bt_modificar_he.setText("Modificar");

        bt_eliminar_he.setText("Eliminar");

        jl_xheroes.setModel(new DefaultListModel()
        );
        jScrollPane7.setViewportView(jl_xheroes);

        javax.swing.GroupLayout super_heroesLayout = new javax.swing.GroupLayout(super_heroes.getContentPane());
        super_heroes.getContentPane().setLayout(super_heroesLayout);
        super_heroesLayout.setHorizontalGroup(
            super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(super_heroesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_fuerza_he, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre_he, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_debilidad_he, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(28, 28, 28))
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addComponent(sp_mental_he, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(sp_fisica_he, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_poder_he, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(super_heroesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bt_agregar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(bt_modificar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(super_heroesLayout.createSequentialGroup()
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        super_heroesLayout.setVerticalGroup(
            super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(super_heroesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(tf_poder_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(super_heroesLayout.createSequentialGroup()
                        .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_debilidad_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(sp_fuerza_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sp_mental_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(sp_fisica_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(super_heroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_agregar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_modificar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_eliminar_he, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel21.setText("Agilidad mental");

        jLabel22.setText("Agilidad Fisica");

        jLabel23.setText("Escuadron");

        jLabel24.setText("Poder");

        jLabel25.setText("fuerza");

        jLabel26.setText("Debilidad");

        jLabel27.setText("Nombre");

        jLabel28.setText("Villanos");

        jl_villanos.setModel(new DefaultListModel()
        );
        jScrollPane4.setViewportView(jl_villanos);

        bt_agregar_vi.setText("Agregar");
        bt_agregar_vi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_viMouseClicked(evt);
            }
        });

        bt_modificar_vi.setText("Modificar");

        bt_eliminar_vi.setText("Eliminar");

        jl_xvillanos.setModel(new DefaultListModel()
        );
        jScrollPane6.setViewportView(jl_xvillanos);

        javax.swing.GroupLayout VillanosLayout = new javax.swing.GroupLayout(Villanos.getContentPane());
        Villanos.getContentPane().setLayout(VillanosLayout);
        VillanosLayout.setHorizontalGroup(
            VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VillanosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(bt_agregar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(bt_modificar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(VillanosLayout.createSequentialGroup()
                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VillanosLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VillanosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25))
                        .addGap(41, 41, 41)
                        .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_debilidad_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_mental_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_fuerza_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213)
                        .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VillanosLayout.createSequentialGroup()
                                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(34, 34, 34)
                                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_poder_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VillanosLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sp_fisica_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(VillanosLayout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VillanosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27)
                        .addComponent(jLabel26))
                    .addContainerGap(817, Short.MAX_VALUE)))
        );
        VillanosLayout.setVerticalGroup(
            VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VillanosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VillanosLayout.createSequentialGroup()
                        .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(sp_fuerza_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(68, 68, 68))
                    .addGroup(VillanosLayout.createSequentialGroup()
                        .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_poder_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_debilidad_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sp_mental_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(sp_fisica_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_modificar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_eliminar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_agregar_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(VillanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VillanosLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLabel27)
                    .addGap(22, 22, 22)
                    .addComponent(jLabel26)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );

        jLabel1.setText("Escuadron Villanos");

        jLabel2.setText("Localidad de su base");

        jLabel3.setText("Nombre");

        jLabel4.setText("Lema");

        jLabel6.setText("Tipo de escuadron");

        tf_tipo_es_vi.setText("Escuadron villanos");

        jl_escuadron_villanos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_escuadron_villanos);

        bt_agregar_es_vi.setText("Agregar");
        bt_agregar_es_vi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_es_viMouseClicked(evt);
            }
        });

        bt_mod_es_vi.setText("modificar");
        bt_mod_es_vi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mod_es_viMouseClicked(evt);
            }
        });

        bt_elim_es_vi.setText("Eliminar");
        bt_elim_es_vi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_elim_es_viMouseClicked(evt);
            }
        });

        jLabel5.setText("Lider");

        javax.swing.GroupLayout Escuadron_villanoLayout = new javax.swing.GroupLayout(Escuadron_villano.getContentPane());
        Escuadron_villano.getContentPane().setLayout(Escuadron_villanoLayout);
        Escuadron_villanoLayout.setHorizontalGroup(
            Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_tipo_es_vi, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(tf_lema_es_vi, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(cb_villanos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombre_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_localidad_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                                        .addComponent(bt_agregar_es_vi)
                                        .addGap(69, 69, 69)
                                        .addComponent(bt_mod_es_vi)
                                        .addGap(78, 78, 78)
                                        .addComponent(bt_elim_es_vi))))))
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel3)
                    .addContainerGap(462, Short.MAX_VALUE)))
        );
        Escuadron_villanoLayout.setVerticalGroup(
            Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2))
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(tf_nombre_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_localidad_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_lema_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_tipo_es_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_villanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_agregar_es_vi)
                    .addComponent(bt_mod_es_vi)
                    .addComponent(bt_elim_es_vi))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(Escuadron_villanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Escuadron_villanoLayout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jLabel3)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );

        jl_escuadron_heroes.setModel(new DefaultListModel()
        );
        jScrollPane2.setViewportView(jl_escuadron_heroes);

        jLabel7.setText("Tipo de escuadron");

        bt_elim_es_he.setText("Eliminar");
        bt_elim_es_he.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_elim_es_heMouseClicked(evt);
            }
        });

        jLabel8.setText("Nombre");

        jLabel9.setText("Escruadron Super Héroes");

        bt_mod_es_he.setText("modificar");
        bt_mod_es_he.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mod_es_heMouseClicked(evt);
            }
        });

        bt_agregar_es_he.setText("Agregar");
        bt_agregar_es_he.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_es_heMouseClicked(evt);
            }
        });

        jLabel10.setText("Localidad de su base");

        jLabel11.setText("Lema");

        tf_tipo_es_he.setText("Escuadron heroes");
        tf_tipo_es_he.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tipo_es_heActionPerformed(evt);
            }
        });

        jLabel12.setText("Lider");

        javax.swing.GroupLayout Escuadron_heroeLayout = new javax.swing.GroupLayout(Escuadron_heroe.getContentPane());
        Escuadron_heroe.getContentPane().setLayout(Escuadron_heroeLayout);
        Escuadron_heroeLayout.setHorizontalGroup(
            Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                        .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)))
                            .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel11)
                                .addGap(134, 134, 134)))
                        .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre_es_he, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(tf_localidad_es_he, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(tf_lema_es_he)
                            .addComponent(cb_heroes, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tipo_es_he)))
                    .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                                .addComponent(bt_agregar_es_he)
                                .addGap(62, 62, 62)
                                .addComponent(bt_mod_es_he)
                                .addGap(99, 99, 99)
                                .addComponent(bt_elim_es_he))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Escuadron_heroeLayout.setVerticalGroup(
            Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Escuadron_heroeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(39, 39, 39)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre_es_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_localidad_es_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(Escuadron_heroeLayout.createSequentialGroup()
                        .addComponent(tf_lema_es_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(24, 24, 24)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(cb_heroes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_tipo_es_he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Escuadron_heroeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_elim_es_he)
                    .addComponent(bt_mod_es_he)
                    .addComponent(bt_agregar_es_he))
                .addGap(41, 41, 41))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Power Squad");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jTree1);

        generar_arbol.setText("Generar Arbol");
        generar_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generar_arbolMouseClicked(evt);
            }
        });

        menu.setText("Power Squad");

        jMenu5.setText("Escuadrones");

        jmi_escuadron_villano.setText("Escuadron de villano");
        jmi_escuadron_villano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_escuadron_villanoActionPerformed(evt);
            }
        });
        jMenu5.add(jmi_escuadron_villano);

        jmi_escuadronheroe.setText("Escuadron de heroes");
        jmi_escuadronheroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_escuadronheroeActionPerformed(evt);
            }
        });
        jMenu5.add(jmi_escuadronheroe);

        menu.add(jMenu5);

        heroes_menu.setText("Super héroes");
        heroes_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroes_menuActionPerformed(evt);
            }
        });
        menu.add(heroes_menu);

        villanos_menu.setText("Villanos");
        villanos_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villanos_menuActionPerformed(evt);
            }
        });
        menu.add(villanos_menu);

        jMenuBar1.add(menu);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generar_arbol)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generar_arbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void villanos_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villanos_menuActionPerformed
        // TODO add your handling code here:
        Villanos.setModal(true);
        Villanos.pack();
        Villanos.setLocationRelativeTo(this);
        Villanos.setVisible(true);
    }//GEN-LAST:event_villanos_menuActionPerformed

    private void heroes_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroes_menuActionPerformed
        // TODO add your handling code here:
        super_heroes.setModal(true);
        super_heroes.pack();
        super_heroes.setLocationRelativeTo(this);
        super_heroes.setVisible(true);
        
    }//GEN-LAST:event_heroes_menuActionPerformed

    private void tf_tipo_es_heActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tipo_es_heActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tipo_es_heActionPerformed

    private void bt_agregar_es_heMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_es_heMouseClicked
        // TODO add your handling code here:
        //Agregar escuadron heroes
        Escuadron_SuperHeroes x;
        try {
            String nombre=tf_nombre_es_he.getText();
            String localidad=tf_localidad_es_he.getText();
            String lema=tf_lema_es_he.getText();
            String tipo=tf_tipo_es_he.getText();
            String lider;
            if(cb_heroes==null){
                 lider=null;
            }else{
                 lider=(String) cb_heroes.getSelectedItem();
            }
            
            //tring nombre, String localidad, String lider, String lema, String tipo_Escuadron
            
               escuadron_heroes.add(new Escuadron_SuperHeroes(nombre, localidad, lider, lema, tipo));
               heroes_menu.setEnabled(true);
//               Escuadron_SuperHeroes j = new Escuadron_SuperHeroes(nombre, localidad, lider, lema, tipo);
//                DefaultListModel modelo = (DefaultListModel) jl_escuadron_heroes.getModel();
//                modelo.addElement(j);
//                DefaultListModel modelolist = (DefaultListModel) jl_escuadron_heroes.getModel();
//                modelolist.addElement(j);
//              
//                DefaultComboBoxModel model=(DefaultComboBoxModel)cb_heroes.getModel();
//               model.addElement(nombre);
//               cb_heroes.setModel(model);
//            escuadron_heroes.add(new Escuadron_SuperHeroes(nombre, localidad, lider, lema, tipo));
            
            DefaultListModel modelo=(DefaultListModel)jl_escuadron_heroes.getModel();
            modelo.addElement(new Escuadron_SuperHeroes(nombre, localidad, lider, lema, tipo));
           jl_escuadron_heroes.setModel(modelo);
           
           
           DefaultListModel modelo2=(DefaultListModel)jl_xheroes.getModel();
            modelo2.addElement(new Escuadron_SuperHeroes(nombre, localidad, lider, lema, tipo));
           jl_xheroes.setModel(modelo2);
            JOptionPane.showMessageDialog(Escuadron_heroe, "Se añadio exitosamente el escuadron");
          
            
            //resetear 
        tf_nombre_es_he.setText("");
        tf_localidad_es_he.setText("");
        tf_lema_es_he.setText("");
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(Escuadron_heroe, "ocurrio un error y no se guardaron los datos");
        }
        
    }//GEN-LAST:event_bt_agregar_es_heMouseClicked

    private void jmi_escuadron_villanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_escuadron_villanoActionPerformed
        // TODO add your handling code here:
        Escuadron_villano.setModal(true);
        Escuadron_villano.pack();
        Escuadron_villano.setLocationRelativeTo(this);
        Escuadron_villano.setVisible(true);
    }//GEN-LAST:event_jmi_escuadron_villanoActionPerformed

    private void jmi_escuadronheroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_escuadronheroeActionPerformed
        // TODO add your handling code here:
        Escuadron_heroe.setModal(true);
        Escuadron_heroe.pack();
        Escuadron_heroe.setLocationRelativeTo(this);
        Escuadron_heroe.setVisible(true);
    }//GEN-LAST:event_jmi_escuadronheroeActionPerformed

    private void bt_agregar_es_viMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_es_viMouseClicked
    try {
            String nombre=tf_nombre_es_vi.getText();
            String localidad=tf_localidad_es_vi.getText();
            String lema=tf_lema_es_vi.getText();
            String tipo=tf_tipo_es_vi.getText();
            String lider;
            if(cb_villanos==null){
                 lider=null;
            }else{
                 lider=(String) cb_villanos.getSelectedItem();
            }
            
            //tring nombre, String localidad, String lider, String lema, String tipo_Escuadron
            
               escuadron_villanos.add(new Escuadron_villanos(nombre, localidad, lider, lema, tipo));
               villanos_menu.setEnabled(true);
//               
            DefaultListModel modelo=(DefaultListModel)jl_escuadron_villanos.getModel();
            modelo.addElement(new Escuadron_villanos(nombre, localidad, lider, lema, tipo));
           jl_escuadron_villanos.setModel(modelo);
           
           DefaultListModel modelo2=(DefaultListModel)jl_xvillanos.getModel();
            modelo2.addElement(new Escuadron_villanos(nombre, localidad, lider, tipo, lema));
           jl_xvillanos.setModel(modelo2);
           
            JOptionPane.showMessageDialog(Villanos, "Se añadio exitosamente el escuadron");
          
            
            //resetear 
        tf_nombre_es_vi.setText("");
        tf_localidad_es_vi.setText("");
        tf_lema_es_vi.setText("");
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(Escuadron_villano, "ocurrio un error y no se guardaron los datos");
        }
        
        
    }//GEN-LAST:event_bt_agregar_es_viMouseClicked

    private void bt_mod_es_heMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mod_es_heMouseClicked
        // TODO add your handling code here:
        //modificar heroe
//        String nombre=JOptionPane.showInputDialog("Ingrese nuevo nombre:");
//        DefaultListModel modelo = (DefaultListModel)jl_personas.getModel();
//        int d=jl_personas.getSelectedIndex();
//        ((Persona)modelo.get(d)).setNombre(nombre);
        int d=jl_escuadron_heroes.getSelectedIndex();
        if(d>=0){
            String nombre=JOptionPane.showInputDialog("nuevo nombre");
            String localidad=JOptionPane.showInputDialog("nueva localidad");
            String lema=JOptionPane.showInputDialog("nuevo lema");
            
        DefaultListModel modelo = (DefaultListModel)jl_escuadron_heroes.getModel();
     
        ((Escuadron_SuperHeroes)modelo.get(d)).setNombre(nombre);
        ((Escuadron_SuperHeroes)modelo.get(d)).setLocalidad(localidad);
        ((Escuadron_SuperHeroes)modelo.get(d)).setLema(lema);
         escuadron_heroes.get(d).setLocalidad(localidad);
           escuadron_heroes.get(d).setLema(lema);
        }else{
            JOptionPane.showMessageDialog(Escuadron_heroe, "fila no seleccionada"
                    + "");
        }
            
            
                    //modificar el lider pendiente
                    
//            DefaultComboBoxModel model=(DefaultComboBoxModel)cb_heroes.getModel();
//               model.addElement(nombre);
//               cb_heroes.setModel(model);

    }//GEN-LAST:event_bt_mod_es_heMouseClicked

    private void bt_elim_es_heMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_elim_es_heMouseClicked
        // TODO add your handling code here:
         int d=jl_escuadron_heroes.getSelectedIndex();
        if(d>=0){
             DefaultListModel modelo = (DefaultListModel)jl_escuadron_heroes.getModel();
     
        modelo.remove(d);
        escuadron_heroes.remove(d);
        }
    }//GEN-LAST:event_bt_elim_es_heMouseClicked

    private void bt_mod_es_viMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mod_es_viMouseClicked
        // TODO add your handling code here:
        int d=jl_escuadron_villanos.getSelectedIndex();
        if(d>=0){
            String nombre=JOptionPane.showInputDialog("nuevo nombre");
            String localidad=JOptionPane.showInputDialog("nueva localidad");
            String lema=JOptionPane.showInputDialog("nuevo lema");
            
        DefaultListModel modelo = (DefaultListModel)jl_escuadron_villanos.getModel();
     
        ((Escuadron_SuperHeroes)modelo.get(d)).setNombre(nombre);
        ((Escuadron_SuperHeroes)modelo.get(d)).setLocalidad(localidad);
        ((Escuadron_SuperHeroes)modelo.get(d)).setLema(lema);
         escuadron_villanos.get(d).setLocalidad(localidad);
           escuadron_villanos.get(d).setLema(lema);
        }else{
            JOptionPane.showMessageDialog(Escuadron_villano, "fila no seleccionada"
                    + "");
        }
        
    }//GEN-LAST:event_bt_mod_es_viMouseClicked

    private void bt_elim_es_viMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_elim_es_viMouseClicked
        // TODO add your handling code here:
         int d=jl_escuadron_villanos.getSelectedIndex();
        if(d>=0){
             DefaultListModel modelo = (DefaultListModel)jl_escuadron_villanos.getModel();
     
        modelo.remove(d);
        escuadron_villanos.remove(d);
        }else{
            
        
         JOptionPane.showMessageDialog(Escuadron_villano, "fila no seleccionada"
                    + "");
        }
    }//GEN-LAST:event_bt_elim_es_viMouseClicked

    private void bt_agregar_viMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_viMouseClicked
        // TODO add your handling code here:
        
         try {
             
            
           
            String nombre=tf_nombre_vi.getText();
            String poder=tf_poder_vi.getText();
            String debilidad=tf_debilidad_vi.getText();
            Escuadron_villanos  escuadron;
            if(cb_villanos==null){
                 escuadron=null;
            }else{
                 escuadron= (Escuadron_villanos) cb_villanos.getSelectedItem();
            }
            int fuerza = (Integer)sp_fuerza_vi.getValue();
            int  ag_fisica= (Integer)sp_fisica_vi.getValue();
            int ag_mental= (Integer)sp_mental_vi.getValue();
                    
//            String nombre, String poder, String debilidad, String escuadron, int fuerza, int agilidad_fisica, int agilidad_mental
            villanos.add(new Villanos(nombre, poder, debilidad, escuadron, fuerza, ag_fisica, ag_mental));
            
            
            
            
            DefaultListModel modelo=(DefaultListModel)jl_villanos.getModel();
            modelo.addElement(new Villanos(nombre, poder, debilidad, escuadron, fuerza, ag_fisica, ag_mental));
           jl_villanos.setModel(modelo);
            JOptionPane.showMessageDialog(Villanos, "Se añadio exitosamente el villano");
          
            
            //resetear 
             tf_nombre_vi.setText("");
             tf_poder_vi.setText("");
            tf_debilidad_vi.setText("");
            cb_heroes.setSelectedItem(0);
            sp_fuerza_vi.setValue(0);
            sp_fisica_vi.setValue(0);
            sp_mental_vi.setValue(0);
            
         
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(Villanos, "ocurrio un error y no se guardaron los datos");
        }
        
    }//GEN-LAST:event_bt_agregar_viMouseClicked

    private void generar_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generar_arbolMouseClicked
        // TODO add your handling code here:
        
        
        
//        for (int i = 0; i < grupo1.size()-2; i++) {
//            String cruce="Cruce #1";
//           
//                
//            int centinela=-1;//recorrido en anchura
//            for (int j = 0; j < raiz.getChildCount(); j++) {
//                if(raiz.getChildAt(j).toString().equals(cruce)){
//////                    si ya existe le agrega la persona
//                DefaultMutableTreeNode p;
//                 
//                 if(i==0){
//                    String equipo1=(String)grupo1.get(0);
//                     String equipo2=(String)grupo1.get(1);
//                
//                  p=new DefaultMutableTreeNode(new Enfrentamientos(equipo1, equipo2));
//                  }else{
//                     String equipo1=(String)grupo1.get(2);
//                     String equipo2=(String)grupo1.get(3);
//                    p=new DefaultMutableTreeNode(new Enfrentamientos(equipo1, equipo2));
//                 }
//                 ((DefaultMutableTreeNode)raiz.getChildAt(j)).add(p);
//                 centinela=1;
//             }
//            }
//             sino existe la nacionalidad
//             
//             if(centinela==-1){
//                 
//                 crera nodo de nacionalidad y crer nodo de persona
//                 DefaultMutableTreeNode n=new DefaultMutableTreeNode(cruce);
//                 DefaultMutableTreeNode p;
//                 
//                  if(i==0){
//                    String equipo1=(String)grupo1.get(0);
//                     String equipo2=(String)grupo1.get(1);
//                
//                 p=new DefaultMutableTreeNode(new Enfrentamientos(equipo1, equipo2));
//                  }else{
//                     String equipo1=(String)grupo1.get(2);
//                     String equipo2=(String)grupo1.get(2);
//                      p=new DefaultMutableTreeNode(new Enfrentamientos(equipo1, equipo2));
//                 }
//             
//                 n.add(p);
//                 raiz.add(n);
//             }//fin por 
//             modeloARBOL.reload();
    }//GEN-LAST:event_generar_arbolMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Power_Squad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Escuadron_heroe;
    private javax.swing.JDialog Escuadron_villano;
    private javax.swing.JDialog Villanos;
    private javax.swing.JButton bt_agregar_es_he;
    private javax.swing.JButton bt_agregar_es_vi;
    private javax.swing.JButton bt_agregar_he;
    private javax.swing.JButton bt_agregar_vi;
    private javax.swing.JButton bt_elim_es_he;
    private javax.swing.JButton bt_elim_es_vi;
    private javax.swing.JButton bt_eliminar_he;
    private javax.swing.JButton bt_eliminar_vi;
    private javax.swing.JButton bt_mod_es_he;
    private javax.swing.JButton bt_mod_es_vi;
    private javax.swing.JButton bt_modificar_he;
    private javax.swing.JButton bt_modificar_vi;
    private javax.swing.JComboBox<String> cb_heroes;
    private javax.swing.JComboBox<String> cb_villanos;
    private javax.swing.JButton generar_arbol;
    private javax.swing.JMenuItem heroes_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> jl_escuadron_heroes;
    private javax.swing.JList<String> jl_escuadron_villanos;
    private javax.swing.JList<String> jl_heroes;
    private javax.swing.JList<String> jl_villanos;
    private javax.swing.JList<Escuadron_SuperHeroes> jl_xheroes;
    private javax.swing.JList<Escuadron_villanos> jl_xvillanos;
    private javax.swing.JMenuItem jmi_escuadron_villano;
    private javax.swing.JMenuItem jmi_escuadronheroe;
    private javax.swing.JMenu menu;
    private javax.swing.JSpinner sp_fisica_he;
    private javax.swing.JSpinner sp_fisica_vi;
    private javax.swing.JSpinner sp_fuerza_he;
    private javax.swing.JSpinner sp_fuerza_vi;
    private javax.swing.JSpinner sp_mental_he;
    private javax.swing.JSpinner sp_mental_vi;
    private javax.swing.JDialog super_heroes;
    private javax.swing.JTextField tf_debilidad_he;
    private javax.swing.JTextField tf_debilidad_vi;
    private javax.swing.JTextField tf_lema_es_he;
    private javax.swing.JTextField tf_lema_es_vi;
    private javax.swing.JTextField tf_localidad_es_he;
    private javax.swing.JTextField tf_localidad_es_vi;
    private javax.swing.JTextField tf_nombre_es_he;
    private javax.swing.JTextField tf_nombre_es_vi;
    private javax.swing.JTextField tf_nombre_he;
    private javax.swing.JTextField tf_nombre_vi;
    private javax.swing.JTextField tf_poder_he;
    private javax.swing.JTextField tf_poder_vi;
    private javax.swing.JTextField tf_tipo_es_he;
    private javax.swing.JTextField tf_tipo_es_vi;
    private javax.swing.JMenuItem villanos_menu;
    // End of variables declaration//GEN-END:variables
ArrayList<Escuadron_SuperHeroes> escuadron_heroes=new ArrayList();
ArrayList<Escuadron_villanos> escuadron_villanos=new ArrayList();
ArrayList<Villanos> villanos=new ArrayList();
ArrayList<SuperHeroes> heroes=new ArrayList();


}
